version: "3.8"

services:
  app:
    container_name: gemini-task-manager
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev